manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: zephyr
      west-commands: scripts/west-commands.yml
      revision: v1.14.1
      remote: zephyrproject
      import: true
  self:
    path: nrf52840_lpm
